version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
jobs:
  build:
    docker:
      - image: node:12.16.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-{{ checksum "package-lock.json" }}
            - node-
      - run:
          name: Install Front End
          command: npm install
      - save_cache:
          keys: node-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Building Front End
          command: CI=false npm run build
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: build
          to: 's3://www.jacquezwilliams.com'

workflows:
    version: 2
    build-deploy:
      jobs:
        - build:
            filters:
              branches:
                only:
                  - master
