version: 2.1
jobs:
  build:
    docker:
      - image: node:12.16.2
    steps:
      - checkout
      - run:
          name: Test
          command: echo 'Hello, World'
      - run:
          name: Show Files
          command: ls -al

